# Typos spell checker configuration
# https://github.com/crate-ci/typos

[default]
extend-ignore-re = [
  # Ignore URLs
  "https?://[^\\s]+",
  # Ignore hex colors
  "#[0-9a-fA-F]{3,8}",
  # Ignore Google verification tokens and other hashes
  "[a-zA-Z0-9]{40,}",
  # Ignore base64-like strings
  "[A-Za-z0-9+/=]{20,}",
]

[files]
extend-exclude = [
  "node_modules",
  ".next",
  "out",
  "dist",
  "build",
  "*.lock",
  "*.log",
  "*.pdf",
  "*.woff",
  "*.woff2",
  "*.ttf",
  "*.eot",
  "*.otf",
  "pnpm-lock.yaml",
  "package-lock.json",
]

[default.extend-words]
# Personal/Project names
cadunass = "cadunass"
Nass = "Nass"

# UI Libraries & Frameworks
shadcn = "shadcn"
Aceternity = "Aceternity"
radix = "radix"
lucide = "lucide"
tabler = "tabler"

# Build tools & Dev tools
Turbopack = "Turbopack"
turbopack = "turbopack"
biomejs = "biomejs"
postcss = "postcss"
pnpm = "pnpm"
devcontainer = "devcontainer"

# Tech terms
webp = "webp"
webm = "webm"
avif = "avif"

[type.md]
extend-ignore-re = [
  # Ignore inline code
  "`[^`]*`",
  # Ignore code blocks
  "```[\\s\\S]*?```",
]

[type.ts]
extend-ignore-re = [
  # Ignore string literals
  "\"[^\"]*\"",
  "'[^']*'",
]

[type.tsx]
extend-ignore-re = [
  # Ignore string literals
  "\"[^\"]*\"",
  "'[^']*'",
]

