import type { Experience } from '@/types';

export const EXPERIENCE: Experience[] = [
  {
    id: 'alore',
    title: 'Software Engineer',
    company: 'Alore',
    location: 'Remote',
    startDate: '2022-04',
    endDate: 'Present',
    description: [
      'Built architecture for various projects across Web3 and AI, ensuring scalability and maintainability',
      'Designed and implemented a complete and secure HTTP authentication workflow in Rust',
      'Led development of a cryptographically secure and performant Wallet-as-a-Service API in Rust with NextJS client',
      'Successfully migrated a Rust monolithic server to monorepo structure, achieving significant performance increase',
      'Served as core member in developing a generative AI tool for law firms',
      'Led a team to successfully develop and deliver a decentralized application (dApp)',
      'Implemented numerous CI/CD workflows ensuring efficient and automated software delivery',
    ],
    technologies: ['Rust', 'TypeScript', 'Next.js', 'React', 'Web3', 'CI/CD', 'Blockchain'],
  },
  {
    id: 'taric-full-stack',
    title: 'Full Stack Developer',
    company: 'Taric',
    location: 'Joinville, SC',
    startDate: '2021-09',
    endDate: '2022-04',
    description: [
      'Core team member developing an electronic medical record system',
      'Full stack development and expansion focusing on Java and Vue.js',
      'Continuous implementation of new features, tests, bug fixes and code reviews',
      'Contributed to the main company framework system used across various projects',
      'Mentored interns, providing guidance and feedback',
      'Participated in developer-organized technology knowledge-sharing meetings',
    ],
    technologies: ['Java', 'Vue.js', 'Spring', 'SQL'],
  },
  {
    id: 'taric-analyst',
    title: 'Programming Analyst',
    company: 'Taric',
    location: 'Joinville, SC',
    startDate: '2021-06',
    endDate: '2021-09',
    description: [
      'Continued development of rapidly expanding electronic medical record system',
      'Played key role in backend logic and database interactions using Java, Spring, and SQL',
      'Implemented new features and system improvements for healthcare platform used by clinics',
      'Contributed to frontend development using Vue.js with seamless backend integration',
      'Participated in full software development lifecycle including coding, testing, and code review',
    ],
    technologies: ['Java', 'Spring', 'SQL', 'Vue.js'],
  },
  {
    id: 'zitrus-analyst',
    title: 'Programming Analyst',
    company: 'Zitrus',
    location: 'Joinville, SC',
    startDate: '2020-10',
    endDate: '2021-06',
    description: [
      'Led initial frontend development of electronic medical record system using Vue.js',
      'Built core user interface components and features for the EMR platform',
      'Contributed to architecture and implementation of frontend solutions for health clinics',
      'Proactively learned and applied Java, Spring, and SQL to contribute to backend development',
      'Resolved bugs and implemented features across both frontend and backend components',
    ],
    technologies: ['Vue.js', 'Java', 'Spring', 'SQL'],
  },
  {
    id: 'zitrus-intern',
    title: 'Web Development Intern',
    company: 'Zitrus',
    location: 'Joinville, SC',
    startDate: '2019-11',
    endDate: '2020-10',
    description: [
      'Rapidly acquired proficiency in Vue.js and company technology stack',
      'Initiated and contributed significantly to MVP frontend of critical electronic medical record system',
      'Pursued learning opportunities for Java, Spring, and SQL, gaining foundational knowledge',
      'Successfully transitioned understanding into practical application on EMR project',
      'Demonstrated strong initiative leading to full-time Programming Analyst position offer',
    ],
    technologies: ['Vue.js', 'Java', 'Spring', 'SQL'],
  },
  {
    id: 'dalmark-intern',
    title: 'Web Development Intern',
    company: 'Dalmark',
    location: 'Joinville, SC',
    startDate: '2019-02',
    endDate: '2019-11',
    description: [
      'Gained foundational experience in professional web development with React, Node.js, and Groovy',
      'Collaborated on development of functional clock-in/clock-out web page for employees',
      'Implemented features utilizing geolocation API to verify employee proximity',
      'Applied learned concepts to contribute to real-world internal company tool',
      'Participated actively in team development processes including code contribution and testing',
    ],
    technologies: ['React', 'Node.js', 'Groovy'],
  },
];


