name: Spellcheck

on:
  push:
    branches: [main]
    paths:
      - '**.ts'
      - '**.tsx'
      - '**.md'
      - '**.json'
      - 'cspell.json'
      - '.github/workflows/spellcheck.yml'
  pull_request:
    branches: [main]
    paths:
      - '**.ts'
      - '**.tsx'
      - '**.md'
      - '**.json'
      - 'cspell.json'
      - '.github/workflows/spellcheck.yml'
  workflow_dispatch:

# Cancel in-progress runs for same PR/branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  spellcheck:
    name: Check Spelling (CSpell)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run CSpell
        run: pnpm spellcheck
