name: Spellcheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  spellcheck:
    name: Check Spelling
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check spelling
        uses: crate-ci/typos@v1.27.3
        with:
          files: .
          config: .typos.toml

